version: '3.8'

services:
  localstack:
    image: localstack/localstack:3
    ports:
      - '4566:4566'
    environment:
      SERVICES: s3,sqs,dynamodb,events,ses
      DEFAULT_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  order-service:
    build:
      context: .
      dockerfile: apps/order-service/Dockerfile
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
      ORDER_EVENT_BUS_NAME: ecommerce-orders
      ORDERS_TABLE: orders
      SES_FROM_EMAIL: no-reply@ecommerce.example.com
    depends_on:
      localstack:
        condition: service_healthy

  invoice-service:
    build:
      context: .
      dockerfile: apps/invoice-service/Dockerfile
    ports:
      - '3002:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
      ORDER_EVENT_BUS_NAME: ecommerce-orders
      S3_INVOICES_BUCKET: invoices
    depends_on:
      localstack:
        condition: service_healthy

  billing-service:
    build:
      context: .
      dockerfile: apps/billing-service/Dockerfile
    ports:
      - '3003:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
      ORDER_EVENT_BUS_NAME: ecommerce-orders
      STRIPE_SECRET_KEY: sk_test_placeholder
    depends_on:
      localstack:
        condition: service_healthy

  shipping-service:
    build:
      context: .
      dockerfile: apps/shipping-service/Dockerfile
    ports:
      - '3004:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
      ORDER_EVENT_BUS_NAME: ecommerce-orders
      MOCK_CARRIER_BASE_URL: http://shipping-service:3000
    depends_on:
      localstack:
        condition: service_healthy

  notification-service:
    build:
      context: .
      dockerfile: apps/notification-service/Dockerfile
    ports:
      - '3005:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
      ORDER_EVENT_BUS_NAME: ecommerce-orders
      SES_FROM_EMAIL: no-reply@ecommerce.example.com
    depends_on:
      localstack:
        condition: service_healthy

volumes:
  localstack_data:
