export enum ErrorCode {
  // Order errors
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_DUPLICATE = 'ORDER_DUPLICATE',
  ORDER_INVALID_PRODUCT = 'ORDER_INVALID_PRODUCT',
  ORDER_INVALID_CURRENCY = 'ORDER_INVALID_CURRENCY',

  // Payment errors
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_METHOD_INVALID = 'PAYMENT_METHOD_INVALID',

  // Invoice errors
  INVOICE_GENERATION_FAILED = 'INVOICE_GENERATION_FAILED',

  // Shipping errors
  SHIPPING_FAILED = 'SHIPPING_FAILED',

  // General errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
